In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:


# [[3789   29    0    0]
#  [ 125 3530   46    0]
#  [   0   67 3535  117]
#  [   0    0   81 3681]]

In [3]:
confusion_matrix = [[3789  , 29  ,  0  ,  0],
                        [ 125 ,3530  , 46  ,  0],
                        [   0  , 67 ,3535 , 117],
                        [   0 ,   0 ,  81 ,3681]]
classes = ["class1", "class2", "class3", "class4"]

for i in range(len(confusion_matrix)):
    class_count = sum(confusion_matrix[i])
    print("Number of elements in class {}: {}".format(classes[i], class_count))
    TP = confusion_matrix[i][i]
    FP = sum(confusion_matrix[j][i] for j in range(len(confusion_matrix)) if j != i)
    FN = sum(confusion_matrix[i][j] for j in range(len(confusion_matrix)) if j != i)
    TN = sum(confusion_matrix[j][k] for j in range(len(confusion_matrix)) for k in range(len(confusion_matrix)) if j!=i and k!=i)
    precision = TP/(TP+FP)
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    recall = TP/(TP+FN)
    f1_score = 2 * (precision * recall) / (precision + recall)
    MCC = (TP*TN - FP*FN) / ((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))**(1/2)
    print("Metrics for {}:".format(classes[i]))
    print("Precision: {:.3f}".format(precision))
    print("Accuracy: {:.3f}".format(accuracy))
    print("Recall: {:.3f}".format(recall))
    print("F1-score: {:.3f}".format(f1_score))
    print("MCC: {:.3f}\n".format(MCC))


Number of elements in class class1: 3818
Metrics for class1:
Precision: 0.968
Accuracy: 0.990
Recall: 0.992
F1-score: 0.980
MCC: 0.973

Number of elements in class class2: 3701
Metrics for class2:
Precision: 0.974
Accuracy: 0.982
Recall: 0.954
F1-score: 0.964
MCC: 0.952

Number of elements in class class3: 3719
Metrics for class3:
Precision: 0.965
Accuracy: 0.979
Recall: 0.951
F1-score: 0.958
MCC: 0.944

Number of elements in class class4: 3762
Metrics for class4:
Precision: 0.969
Accuracy: 0.987
Recall: 0.978
F1-score: 0.974
MCC: 0.965

