In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# [[3719   99    0    0]
#  [ 189 3276  236    0]
#  [   0  392 3019  308]
#  [   0    0  198 3564]]

In [4]:
confusion_matrix = [[3719 ,  99  ,  0   , 0],
 [ 189, 3276,  236  ,  0],
 [   0,  392, 3019,  308],
 [   0  ,  0 , 198 ,3564]]
classes = ["class1", "class2", "class3", "class4"]

for i in range(len(confusion_matrix)):
    class_count = sum(confusion_matrix[i])
    print("Number of elements in class {}: {}".format(classes[i], class_count))
    TP = confusion_matrix[i][i]
    FP = sum(confusion_matrix[j][i] for j in range(len(confusion_matrix)) if j != i)
    FN = sum(confusion_matrix[i][j] for j in range(len(confusion_matrix)) if j != i)
    TN = sum(confusion_matrix[j][k] for j in range(len(confusion_matrix)) for k in range(len(confusion_matrix)) if j!=i and k!=i)
    precision = TP/(TP+FP)
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    recall = TP/(TP+FN)
    f1_score = 2 * (precision * recall) / (precision + recall)
    MCC = (TP*TN - FP*FN) / ((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))**(1/2)
    print("Metrics for {}:".format(classes[i]))
    print("Precision: {:.3f}".format(precision))
    print("Accuracy: {:.3f}".format(accuracy))
    print("Recall: {:.3f}".format(recall))
    print("F1-score: {:.3f}".format(f1_score))
    print("MCC: {:.3f}\n".format(MCC))


Number of elements in class class1: 3818
Metrics for class1:
Precision: 0.952
Accuracy: 0.981
Recall: 0.974
F1-score: 0.963
MCC: 0.950

Number of elements in class class2: 3701
Metrics for class2:
Precision: 0.870
Accuracy: 0.939
Recall: 0.885
F1-score: 0.877
MCC: 0.837

Number of elements in class class3: 3719
Metrics for class3:
Precision: 0.874
Accuracy: 0.924
Recall: 0.812
F1-score: 0.842
MCC: 0.793

Number of elements in class class4: 3762
Metrics for class4:
Precision: 0.920
Accuracy: 0.966
Recall: 0.947
F1-score: 0.934
MCC: 0.911

