In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# [[3786   32    0    0]
#  [ 109 3551   41    0]
#  [   0   61 3554  104]
#  [   0    0   69 3693]]

In [3]:
confusion_matrix = [[3786 ,  32  ,  0  ,  0],
 [ 109 ,3551  , 41 ,   0],
 [   0 ,  61 ,3554 , 104],
 [   0 ,   0 ,  69 ,3693]]
classes = ["class1", "class2", "class3", "class4"]

for i in range(len(confusion_matrix)):
    class_count = sum(confusion_matrix[i])
    print("Number of elements in class {}: {}".format(classes[i], class_count))
    TP = confusion_matrix[i][i]
    FP = sum(confusion_matrix[j][i] for j in range(len(confusion_matrix)) if j != i)
    FN = sum(confusion_matrix[i][j] for j in range(len(confusion_matrix)) if j != i)
    TN = sum(confusion_matrix[j][k] for j in range(len(confusion_matrix)) for k in range(len(confusion_matrix)) if j!=i and k!=i)
    precision = TP/(TP+FP)
    accuracy = (TP+TN)/(TP+TN+FP+FN)
    recall = TP/(TP+FN)
    f1_score = 2 * (precision * recall) / (precision + recall)
    MCC = (TP*TN - FP*FN) / ((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))**(1/2)
    print("Metrics for {}:".format(classes[i]))
    print("Precision: {:.3f}".format(precision))
    print("Accuracy: {:.3f}".format(accuracy))
    print("Recall: {:.3f}".format(recall))
    print("F1-score: {:.3f}".format(f1_score))
    print("MCC: {:.3f}\n".format(MCC))


Number of elements in class class1: 3818
Metrics for class1:
Precision: 0.972
Accuracy: 0.991
Recall: 0.992
F1-score: 0.982
MCC: 0.975

Number of elements in class class2: 3701
Metrics for class2:
Precision: 0.974
Accuracy: 0.984
Recall: 0.959
F1-score: 0.967
MCC: 0.956

Number of elements in class class3: 3719
Metrics for class3:
Precision: 0.970
Accuracy: 0.982
Recall: 0.956
F1-score: 0.963
MCC: 0.951

Number of elements in class class4: 3762
Metrics for class4:
Precision: 0.973
Accuracy: 0.988
Recall: 0.982
F1-score: 0.977
MCC: 0.969

